// Generated by ego.
// DO NOT EDIT

//line flashes.ego:1

package public

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"
)

func ego_flashes(w io.Writer, req *http.Request, flashes []any) {
//line flashes.ego:9
	_, _ = io.WriteString(w, "\n\n<div class=\"container\">\n  ")
//line flashes.ego:11
	for _, f := range flashes {
//line flashes.ego:12
		_, _ = io.WriteString(w, "\n    <div class=\"row alert alert-primary\" role=\"alert\">\n      ")
//line flashes.ego:13
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(f)))
//line flashes.ego:14
		_, _ = io.WriteString(w, "\n    </div>\n  ")
//line flashes.ego:15
	}
//line flashes.ego:16
	_, _ = io.WriteString(w, "\n</div>\n\n")
//line flashes.ego:18
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
