// Generated by ego.
// DO NOT EDIT

//line footer.ego:1

package public

import "fmt"
import "html"
import "io"
import "context"

import (
	"github.com/contribsys/sparq"
	"github.com/contribsys/sparq/db"
	"net/http"
	"time"
)

func ego_footer(w io.Writer, req *http.Request) {

//line footer.ego:13
	_, _ = io.WriteString(w, "\n<nav class=\"navbar navbar-expand-lg\" style=\"margin-top: 30px\">\n  <div class=\"container-fluid\">\n    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n      <span class=\"navbar-toggler-icon\"></span>\n    </button>\n    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n        <li class=\"nav-item me-md-4\">\n          <p class=\"navbar-text mb-0\">Sparq ")
//line footer.ego:21
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(sparq.Version)))
//line footer.ego:21
	_, _ = io.WriteString(w, "</p>\n        </li>\n        <li class=\"nav-item me-md-4\">\n          <p class=\"navbar-text mb-0\">")
//line footer.ego:24
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(db.InstanceHostname)))
//line footer.ego:24
	_, _ = io.WriteString(w, "</p>\n        </li>\n        <li class=\"nav-item me-md-4\">\n          <p class=\"navbar-text mb-0\">")
//line footer.ego:27
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(time.Now().UTC().Format("2006-01-02 15:04:05Z"))))
//line footer.ego:27
	_, _ = io.WriteString(w, "</p>\n        </li>\n        <li class=\"nav-item\">\n          <a class=\"nav-link disabled\">Disabled</a>\n        </li>\n      </ul>\n    </div>\n  </div>\n</nav>\n")
//line footer.ego:36
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
