// Generated by ego.
// DO NOT EDIT

//line index.ego:1

package public

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"
)

func ego_index(w io.Writer, req *http.Request) {
	ego_layout(w, req, func() {
//line index.ego:10
		_, _ = io.WriteString(w, "\n\n  ")
//line index.ego:11
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(req, "Welcome to your Timeline!"))))
//line index.ego:12
		_, _ = io.WriteString(w, "\n\n  ")
//line index.ego:13
	})
//line index.ego:14
	_, _ = io.WriteString(w, "\n")
//line index.ego:14
	// vim: set ft=html
//line index.ego:15
	_, _ = io.WriteString(w, "\n")
//line index.ego:15
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
