// Generated by ego.
// DO NOT EDIT

//line login.ego:1

package public

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"
)

func ego_login(w http.ResponseWriter, req *http.Request) {
	ego_layout(w, req, func() {
//line login.ego:10
		_, _ = io.WriteString(w, "\n\n")
//line login.ego:11
		flashes(w, req)
//line login.ego:12
		_, _ = io.WriteString(w, "\n<div class=\"container\">\n  <h1>Sign In to Sparq</h1>\n  <form action=\"/login\" method=\"POST\">\n    <div class=\"input-group row mb-3\">\n      <label for=\"username\" class=\"col-sm-2 col-form-label\">Username</label>\n      <div class=\"col-sm-10\">\n        <input type=\"text\" class=\"form-control\" name=\"username\" required>\n      </div>\n    </div>\n    <div class=\"input-group row mb-3\">\n      <label for=\"password\" class=\"col-sm-2 col-form-label\">Password</label>\n      <div class=\"col-sm-10\">\n        <input type=\"password\" class=\"form-control\" name=\"password\" required>\n      </div>\n    </div>\n    <button type=\"submit\" class=\"btn btn-success\">Sign In</button>\n  </form>\n</div>\n\n  ")
//line login.ego:31
	})
//line login.ego:32
	_, _ = io.WriteString(w, "\n")
//line login.ego:32
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
