// Generated by ego.
// DO NOT EDIT

//line nav.ego:1

package public

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"
)

func ego_nav(w io.Writer, r *http.Request) {

//line nav.ego:10
	_, _ = io.WriteString(w, "\n<nav class=\"navbar navbar-expand-lg\" style=\"margin-bottom: 30px;\">\n  <div class=\"container-fluid\">\n    <a class=\"navbar-brand\" href=\"/\"><img src=\"/static/logo-sm.png\" width=\"64\" height=\"64\"/></a>\n    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n      <span class=\"navbar-toggler-icon\"></span>\n    </button>\n    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n        <li class=\"nav-item\">\n          <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\n        </li>\n        <li class=\"nav-item\">\n          <a class=\"nav-link\" href=\"#\">Link</a>\n        </li>\n        <li class=\"nav-item dropdown\">\n          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n            Dropdown\n          </a>\n          <ul class=\"dropdown-menu\">\n            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\n            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n            <li><hr class=\"dropdown-divider\"></li>\n            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n          </ul>\n        </li>\n        ")
//line nav.ego:35
	if loggedIn(r) {
//line nav.ego:36
		_, _ = io.WriteString(w, "\n          <li class=\"nav-item\">\n            <a class=\"nav-link disabled\">")
//line nav.ego:37
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(currentNick(r))))
//line nav.ego:37
		_, _ = io.WriteString(w, "</a>\n          </li>\n        ")
//line nav.ego:39
	}
//line nav.ego:40
	_, _ = io.WriteString(w, "\n      </ul>\n      <form class=\"d-flex\" role=\"search\">\n        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\n      </form>\n    </div>\n  </div>\n</nav>\n")
//line nav.ego:48
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
