// Generated by ego.
// DO NOT EDIT

//line oauth_authorize.ego:1

package public

import "fmt"
import "html"
import "io"
import "context"

import (
	"github.com/contribsys/sparq/model"
	"net/http"
)

func ego_oauth_authorize(w http.ResponseWriter, r *http.Request, client *model.OauthClient) {
	ego_layout(w, r, func() {
//line oauth_authorize.ego:11
		_, _ = io.WriteString(w, "\n\n")
//line oauth_authorize.ego:12
		flashes(w, r)
//line oauth_authorize.ego:13
		_, _ = io.WriteString(w, "\n<div class=\"container\">\n  <h1>Authorize Application?</h1>\n  <p>\n    Do you wish to grant this application access to your Sparq data?\n  </p>\n  <table>\n    <tr><th>Name</th><td>")
//line oauth_authorize.ego:19
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(client.Name)))
//line oauth_authorize.ego:19
		_, _ = io.WriteString(w, "</td></tr>\n    <tr><th>Website</th><td>")
//line oauth_authorize.ego:20
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(client.Website)))
//line oauth_authorize.ego:20
		_, _ = io.WriteString(w, "</td></tr>\n    <tr><th>Scopes</th><td>")
//line oauth_authorize.ego:21
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(client.Scopes)))
//line oauth_authorize.ego:21
		_, _ = io.WriteString(w, "</td></tr>\n  </table>\n\n  <form method=\"POST\">\n    <button type=\"submit\" name=\"Approve\" value=\"1\" class=\"btn btn-success\">")
//line oauth_authorize.ego:25
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(r, "Approve"))))
//line oauth_authorize.ego:25
		_, _ = io.WriteString(w, "</button>\n    <button type=\"submit\" name=\"Deny\" value=\"1\" class=\"btn btn-danger\">")
//line oauth_authorize.ego:26
		_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(t(r, "Deny"))))
//line oauth_authorize.ego:26
		_, _ = io.WriteString(w, "</button>\n  </form>\n</div>\n\n  ")
//line oauth_authorize.ego:30
	})
//line oauth_authorize.ego:31
	_, _ = io.WriteString(w, "\n")
//line oauth_authorize.ego:31
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
