// Generated by ego.
// DO NOT EDIT

//line signup.ego:1

package public

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"
)

func ego_signup(w io.Writer, req *http.Request) {
	ego_layout(w, req, func() {
//line signup.ego:10
		_, _ = io.WriteString(w, "\n\n  Welcome to your Timeline!\n\n  ")
//line signup.ego:13
	})
//line signup.ego:14
	_, _ = io.WriteString(w, "\n")
//line signup.ego:14
	// vim: set ft=html
//line signup.ego:15
	_, _ = io.WriteString(w, "\n")
//line signup.ego:15
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
